#ifndef Ifc_parser_h
#define Ifc_parser_h

#include <boost/algorithm/string.hpp>

#include "Step_parser.hpp"

// Defined types (89)
typedef double Ifc_absorbed_dose_measure;
typedef double Ifc_acceleration_measure;
typedef double Ifc_amount_of_substance_measure;
typedef double Ifc_angular_velocity_measure;
typedef double Ifc_area_measure;
typedef bool Ifc_boolean;
typedef std::vector<int> Ifc_compound_plane_angle_measure;
typedef double Ifc_context_dependent_measure;
typedef unsigned int Ifc_count_measure;
typedef int Ifc_day_in_month_number;
typedef int Ifc_daylight_saving_hour;
typedef std::string Ifc_descriptive_measure;
typedef int Ifc_dimension_count;
typedef double Ifc_dose_equivalent_measure;
typedef double Ifc_dynamic_viscosity_measure;
typedef double Ifc_electric_capacitance_measure;
typedef double Ifc_electric_charge_measure;
typedef double Ifc_electric_conductance_measure;
typedef double Ifc_electric_current_measure;
typedef double Ifc_electric_resistance_measure;
typedef double Ifc_electric_voltage_measure;
typedef double Ifc_energy_measure;
typedef double Ifc_force_measure;
typedef double Ifc_frequency_measure;
typedef std::string Ifc_globally_unique_id;
typedef double Ifc_heat_flux_density_measure;
typedef int Ifc_hour_in_day;
typedef std::string Ifc_identifier;
typedef double Ifc_illuminance_measure;
typedef double Ifc_inductance_measure;
typedef int Ifc_integer;
typedef int Ifc_integer_count_rate_measure;
typedef double Ifc_isothermal_moisture_capacity_measure;
typedef double Ifc_kinematic_viscosity_measure;
typedef std::string Ifc_label;
typedef double Ifc_length_measure;
typedef double Ifc_linear_force_measure;
typedef double Ifc_linear_moment_measure;
typedef double Ifc_linear_stiffness_measure;
typedef double Ifc_linear_velocity_measure;
typedef int Ifc_logical;
typedef double Ifc_luminous_flux_measure;
typedef double Ifc_luminous_intensity_measure;
typedef double Ifc_magnetic_flux_density_measure;
typedef double Ifc_magnetic_flux_measure;
typedef double Ifc_mass_density_measure;
typedef double Ifc_mass_flow_rate_measure;
typedef double Ifc_mass_measure;
typedef int Ifc_minute_in_hour;
typedef double Ifc_modulus_of_elasticity_measure;
typedef double Ifc_modulus_of_subgrade_reaction_measure;
typedef double Ifc_moisture_diffusivity_measure;
typedef double Ifc_molecular_weight_measure;
typedef double Ifc_moment_of_inertia_measure;
typedef double Ifc_monetary_measure;
typedef int Ifc_month_in_year_number;
typedef unsigned int Ifc_numeric_measure;
typedef double Ifc_parameter_value;
typedef double Ifc_planar_force_measure;
typedef double Ifc_plane_angle_measure;
typedef Ifc_length_measure Ifc_positive_length_measure;
typedef Ifc_plane_angle_measure Ifc_positive_plane_angle_measure;
typedef double Ifc_power_measure;
typedef double Ifc_pressure_measure;
typedef double Ifc_radio_activity_measure;
typedef double Ifc_ratio_measure;
typedef double Ifc_real;
typedef double Ifc_rotational_frequency_measure;
typedef double Ifc_rotational_stiffness_measure;
typedef double Ifc_second_in_minute;
typedef double Ifc_shear_modulus_measure;
typedef double Ifc_solid_angle_measure;
typedef double Ifc_specific_heat_capacity_measure;
typedef std::string Ifc_text;
typedef double Ifc_thermal_admittance_measure;
typedef double Ifc_thermal_conductivity_measure;
typedef double Ifc_thermal_resistance_measure;
typedef double Ifc_thermal_transmittance_measure;
typedef double Ifc_thermodynamic_temperature_measure;
typedef double Ifc_time_measure;
typedef int Ifc_time_stamp;
typedef double Ifc_torque_measure;
typedef double Ifc_vapor_permeability_measure;
typedef double Ifc_volume_measure;
typedef double Ifc_volumetric_flow_rate_measure;
typedef int Ifc_year_number;
typedef Ifc_ratio_measure Ifc_normalised_ratio_measure;
typedef Ifc_ratio_measure Ifc_positive_ratio_measure;
typedef std::vector<Ifc_normalised_ratio_measure> Ifc_color_r_g_b;

// Enums (116)
typedef std::string Ifc_actuator_fail_position_enum;
typedef std::string Ifc_actuator_type_enum;
typedef std::string Ifc_address_type_enum;
typedef std::string Ifc_aggregator_enum;
typedef std::string Ifc_ahead_or_behind;
typedef std::string Ifc_air_flow_type_enum;
typedef std::string Ifc_air_terminal_box_enum;
typedef std::string Ifc_air_terminal_core_type_enum;
typedef std::string Ifc_air_terminal_face_type_enum;
typedef std::string Ifc_air_terminal_finish_type_enum;
typedef std::string Ifc_air_terminal_mounting_type_enum;
typedef std::string Ifc_approval_status_enum;
typedef std::string Ifc_benchmark_enum;
typedef std::string Ifc_boiler_type_enum;
typedef std::string Ifc_boolean_operator;
typedef std::string Ifc_built_in_type_enum;
typedef std::string Ifc_change_action_enum;
typedef std::string Ifc_change_order_status_enum;
typedef std::string Ifc_chiller_type_enum;
typedef std::string Ifc_coil_flow_arrangement_enum;
typedef std::string Ifc_coil_type_enum;
typedef std::string Ifc_compressor_type_enum;
typedef std::string Ifc_connection_type_enum;
typedef std::string Ifc_constraint_enum;
typedef std::string Ifc_constraint_intent_enum;
typedef std::string Ifc_cooling_tower_type_enum;
typedef std::string Ifc_cost_modifier_basis_enum;
typedef std::string Ifc_cost_operator_enum;
typedef std::string Ifc_cost_use_enum;
typedef std::string Ifc_covering_type_enum;
typedef std::string Ifc_currency_enum;
typedef std::string Ifc_damper_sizing_method_enum;
typedef std::string Ifc_damper_type_enum;
typedef std::string Ifc_derived_unit_enum;
typedef std::string Ifc_direction_sense_enum;
typedef std::string Ifc_discrete_element_type_enum;
typedef std::string Ifc_distribution_flow_element_type_enum;
typedef std::string Ifc_document_confidentiality_enum;
typedef std::string Ifc_document_status_enum;
typedef std::string Ifc_door_panel_operation_enum;
typedef std::string Ifc_door_panel_position_enum;
typedef std::string Ifc_door_style_construction_enum;
typedef std::string Ifc_door_style_operation_enum;
typedef std::string Ifc_electric_current_enum;
typedef std::string Ifc_electrical_appliance_type_enum;
typedef std::string Ifc_element_composition_enum;
typedef std::string Ifc_energy_source_enum;
typedef std::string Ifc_fan_arrangement_enum;
typedef std::string Ifc_fan_discharge_type_enum;
typedef std::string Ifc_fan_drive_arrangement_enum;
typedef std::string Ifc_fan_mounting_type_enum;
typedef std::string Ifc_fan_pressure_class_enum;
typedef std::string Ifc_fan_rotation_enum;
typedef std::string Ifc_fan_wheel_type_enum;
typedef std::string Ifc_flow_direction_enum;
typedef std::string Ifc_flow_fitting_type_enum;
typedef std::string Ifc_flow_segment_type_enum;
typedef std::string Ifc_heat_exchanger_arrangement_enum;
typedef std::string Ifc_heat_exchanger_type_enum;
typedef std::string Ifc_hydronic_heater_type_enum;
typedef std::string Ifc_internal_or_external_enum;
typedef std::string Ifc_inventory_type_enum;
typedef std::string Ifc_joint_enum;
typedef std::string Ifc_layer_set_direction_enum;
typedef std::string Ifc_loss_or_gain_enum;
typedef std::string Ifc_maintenance_type_enum;
typedef std::string Ifc_metric_data_enum;
typedef std::string Ifc_moter_connection_type_enum;
typedef std::string Ifc_motor_housing_enum;
typedef std::string Ifc_motor_winding_enum;
typedef std::string Ifc_multiplier_or_divider;
typedef std::string Ifc_object_type_enum;
typedef std::string Ifc_objective_enum;
typedef std::string Ifc_occupant_type_enum;
typedef std::string Ifc_outlet_type_enum;
typedef std::string Ifc_permeable_covering_operation_enum;
typedef std::string Ifc_physical_or_virtual_enum;
typedef std::string Ifc_port_connection_type_enum;
typedef std::string Ifc_primary_fitting_enum;
typedef std::string Ifc_priority_enum;
typedef std::string Ifc_profile_type_enum;
typedef std::string Ifc_pump_base_type_enum;
typedef std::string Ifc_pump_type_enum;
typedef std::string Ifc_purchase_order_status_enum;
typedef std::string Ifc_quantity_round_off_basis_enum;
typedef std::string Ifc_railing_type_enum;
typedef std::string Ifc_ramp_type_enum;
typedef std::string Ifc_requirement_or_criteria_enum;
typedef std::string Ifc_resource_consumption_enum;
typedef std::string Ifc_risk_type_enum;
typedef std::string Ifc_role_enum;
typedef std::string Ifc_roof_type_enum;
typedef std::string Ifc_s_i_prefix;
typedef std::string Ifc_s_i_unit_name;
typedef std::string Ifc_sanitary_terminal_type_enum;
typedef std::string Ifc_sensor_type_enum;
typedef std::string Ifc_sequence_enum;
typedef std::string Ifc_slab_type_enum;
typedef std::string Ifc_stair_type_enum;
typedef std::string Ifc_state_enum;
typedef std::string Ifc_surface_side_enum;
typedef std::string Ifc_task_milestone_enum;
typedef std::string Ifc_task_status_enum;
typedef std::string Ifc_thermal_load_type_enum;
typedef std::string Ifc_transition_code;
typedef std::string Ifc_transport_element_type_enum;
typedef std::string Ifc_trimming_preference;
typedef std::string Ifc_unit_enum;
typedef std::string Ifc_valve_enum;
typedef std::string Ifc_window_panel_operation_enum;
typedef std::string Ifc_window_panel_position_enum;
typedef std::string Ifc_window_style_construction_enum;
typedef std::string Ifc_window_style_operation_enum;
typedef std::string Ifc_work_control_type_enum;
typedef std::string Ifc_work_order_risk_type_enum;
typedef std::string Ifc_work_order_status_enum;

// Forward declarations (370)
struct Ifc_2_d_composite_curve;
struct Ifc_action_time_control;
struct Ifc_actor;
struct Ifc_actor_role;
struct Ifc_actuator;
struct Ifc_address;
struct Ifc_air_filter;
struct Ifc_air_terminal;
struct Ifc_air_terminal_box;
struct Ifc_application;
struct Ifc_approval;
struct Ifc_approval_usage;
struct Ifc_arbitrary_closed_profile_def;
struct Ifc_arbitrary_open_profile_def;
struct Ifc_arbitrary_profile_def_with_voids;
struct Ifc_assessory;
struct Ifc_asset;
struct Ifc_axis_1_placement;
struct Ifc_axis_2_placement_2_d;
struct Ifc_axis_2_placement_3_d;
struct Ifc_beam;
struct Ifc_boiler;
struct Ifc_boolean_clipping_result;
struct Ifc_boolean_result;
struct Ifc_bounded_curve;
struct Ifc_bounded_surface;
struct Ifc_bounding_box;
struct Ifc_boxed_half_space;
struct Ifc_budget;
struct Ifc_building;
struct Ifc_building_element;
struct Ifc_building_element_proxy;
struct Ifc_building_storey;
struct Ifc_built_in;
struct Ifc_c_m_doc_package;
struct Ifc_calendar_date;
struct Ifc_cartesian_point;
struct Ifc_cartesian_transformation_operator;
struct Ifc_cartesian_transformation_operator_2_d;
struct Ifc_cartesian_transformation_operator_2_dnon_uniform;
struct Ifc_cartesian_transformation_operator_3_d;
struct Ifc_cartesian_transformation_operator_3_dnon_uniform;
struct Ifc_change_order;
struct Ifc_chiller;
struct Ifc_circle;
struct Ifc_circle_profile_def;
struct Ifc_classification;
struct Ifc_classification_item;
struct Ifc_classification_item_relationship;
struct Ifc_classification_notation;
struct Ifc_classification_notation_facet;
struct Ifc_classification_reference;
struct Ifc_closed_shell;
struct Ifc_coil;
struct Ifc_column;
struct Ifc_compartment;
struct Ifc_complex_property;
struct Ifc_composite_curve;
struct Ifc_composite_curve_segment;
struct Ifc_composite_profile_def;
struct Ifc_compressor;
struct Ifc_conic;
struct Ifc_connected_face_set;
struct Ifc_connection_constraint;
struct Ifc_connection_curve_geometry;
struct Ifc_connection_geometry;
struct Ifc_connection_point_geometry;
struct Ifc_connection_port_geometry;
struct Ifc_connection_surface_geometry;
struct Ifc_constraint;
struct Ifc_constraint_aggregation_relationship;
struct Ifc_constraint_usage;
struct Ifc_construction_equipment_resource;
struct Ifc_construction_material_resource;
struct Ifc_construction_product_resource;
struct Ifc_context_dependent_unit;
struct Ifc_control;
struct Ifc_control_element;
struct Ifc_controller;
struct Ifc_conversion_based_unit;
struct Ifc_cooling_tower;
struct Ifc_coordinated_universal_time_offset;
struct Ifc_cost;
struct Ifc_cost_modifier;
struct Ifc_cost_modifier_value;
struct Ifc_cost_quantity;
struct Ifc_cost_schedule;
struct Ifc_cost_value;
struct Ifc_cost_value_relationship;
struct Ifc_covering;
struct Ifc_crew_resource;
struct Ifc_csg_solid;
struct Ifc_curtain_wall;
struct Ifc_curve;
struct Ifc_curve_bounded_plane;
struct Ifc_damper;
struct Ifc_date_and_time;
struct Ifc_derived_profile_def;
struct Ifc_derived_unit;
struct Ifc_derived_unit_element;
struct Ifc_dimensional_exponents;
struct Ifc_direction;
struct Ifc_directional_light_source;
struct Ifc_discrete_element;
struct Ifc_distribution_element;
struct Ifc_distribution_flow_element;
struct Ifc_document_electronic_format;
struct Ifc_document_information;
struct Ifc_document_information_relationship;
struct Ifc_document_reference;
struct Ifc_door;
struct Ifc_door_lining_properties;
struct Ifc_door_panel_properties;
struct Ifc_door_style;
struct Ifc_edge;
struct Ifc_edge_curve;
struct Ifc_electric_motor;
struct Ifc_electrical_appliance;
struct Ifc_electrical_base_properties;
struct Ifc_electrical_element;
struct Ifc_electrical_extended_properties;
struct Ifc_element;
struct Ifc_element_quantity;
struct Ifc_elementary_surface;
struct Ifc_ellipse;
struct Ifc_ellipse_profile_def;
struct Ifc_equipment_element;
struct Ifc_equipment_standard;
struct Ifc_extended_material_properties;
struct Ifc_external_reference;
struct Ifc_extruded_area_solid;
struct Ifc_face;
struct Ifc_face_based_surface_model;
struct Ifc_face_bound;
struct Ifc_face_outer_bound;
struct Ifc_face_surface;
struct Ifc_faceted_brep;
struct Ifc_faceted_brep_with_voids;
struct Ifc_fan;
struct Ifc_flow_controller;
struct Ifc_flow_fitting;
struct Ifc_flow_segment;
struct Ifc_flow_terminal;
struct Ifc_fluid_flow_properties;
struct Ifc_fluid_moving_device;
struct Ifc_furnishing_element;
struct Ifc_furniture;
struct Ifc_furniture_standard;
struct Ifc_general_material_properties;
struct Ifc_geometric_representation_context;
struct Ifc_geometric_representation_item;
struct Ifc_geometric_set;
struct Ifc_grid;
struct Ifc_grid_axis;
struct Ifc_grid_placement;
struct Ifc_group;
struct Ifc_half_space_solid;
struct Ifc_heat_exchanger;
struct Ifc_heat_transfer_device;
struct Ifc_hydronic_heater;
struct Ifc_hygroscopic_material_properties;
struct Ifc_inventory;
struct Ifc_ishape_profile_def;
struct Ifc_labor_resource;
struct Ifc_library_information;
struct Ifc_library_reference;
struct Ifc_light_fixture;
struct Ifc_line;
struct Ifc_local_placement;
struct Ifc_local_time;
struct Ifc_loop;
struct Ifc_maintenance_record;
struct Ifc_maintenance_work_order;
struct Ifc_manifold_solid_brep;
struct Ifc_manufacturer_information;
struct Ifc_mapped_item;
struct Ifc_material;
struct Ifc_material_classification_relationship;
struct Ifc_material_layer;
struct Ifc_material_layer_set;
struct Ifc_material_layer_set_usage;
struct Ifc_material_list;
struct Ifc_material_properties;
struct Ifc_measure_with_unit;
struct Ifc_mechanical_material_properties;
struct Ifc_metric;
struct Ifc_metric_benchmark;
struct Ifc_metric_value;
struct Ifc_monetary_unit;
struct Ifc_move;
struct Ifc_named_unit;
struct Ifc_object;
struct Ifc_object_placement;
struct Ifc_objective;
struct Ifc_occupant;
struct Ifc_offset_curve_2_d;
struct Ifc_offset_curve_3_d;
struct Ifc_open_shell;
struct Ifc_opening_element;
struct Ifc_optical_material_properties;
struct Ifc_organization;
struct Ifc_organization_relationship;
struct Ifc_oriented_edge;
struct Ifc_outlet;
struct Ifc_owner_history;
struct Ifc_path;
struct Ifc_permeable_covering_properties;
struct Ifc_person;
struct Ifc_person_and_organization;
struct Ifc_physical_quantity;
struct Ifc_placement;
struct Ifc_plane;
struct Ifc_point;
struct Ifc_point_light_source;
struct Ifc_poly_loop;
struct Ifc_polygonal_bounded_half_space;
struct Ifc_polyline;
struct Ifc_postal_address;
struct Ifc_presentation_light_source;
struct Ifc_process;
struct Ifc_product;
struct Ifc_product_definition_shape;
struct Ifc_product_representation;
struct Ifc_profile_def;
struct Ifc_project;
struct Ifc_project_order;
struct Ifc_property;
struct Ifc_property_bounded_value;
struct Ifc_property_definition;
struct Ifc_property_enumerated_value;
struct Ifc_property_enumeration;
struct Ifc_property_reference_value;
struct Ifc_property_set;
struct Ifc_property_set_definition;
struct Ifc_property_single_value;
struct Ifc_property_table_value;
struct Ifc_proxy;
struct Ifc_pump;
struct Ifc_purchase_order;
struct Ifc_quantity_area;
struct Ifc_quantity_count;
struct Ifc_quantity_length;
struct Ifc_quantity_volume;
struct Ifc_quantity_weight;
struct Ifc_railing;
struct Ifc_ramp;
struct Ifc_ramp_flight;
struct Ifc_rectangle_profile_def;
struct Ifc_rectangular_trimmed_surface;
struct Ifc_reference_edge;
struct Ifc_reference_face;
struct Ifc_reference_geometry;
struct Ifc_reference_vertex;
struct Ifc_references_cost_document;
struct Ifc_rel_aggregates;
struct Ifc_rel_aggregates_resources;
struct Ifc_rel_assigns;
struct Ifc_rel_assigns_f_m_standard;
struct Ifc_rel_assigns_tasks;
struct Ifc_rel_assigns_to_actor;
struct Ifc_rel_assigns_to_control;
struct Ifc_rel_assigns_to_group;
struct Ifc_rel_assigns_to_process;
struct Ifc_rel_assigns_to_product;
struct Ifc_rel_assigns_to_resource;
struct Ifc_rel_associates;
struct Ifc_rel_associates_classification;
struct Ifc_rel_associates_document;
struct Ifc_rel_associates_library;
struct Ifc_rel_associates_material;
struct Ifc_rel_connects;
struct Ifc_rel_connects_elements;
struct Ifc_rel_connects_path_elements;
struct Ifc_rel_connects_ports;
struct Ifc_rel_contained_in_spatial_structure;
struct Ifc_rel_costs_objects;
struct Ifc_rel_covers_bldg_elements;
struct Ifc_rel_decomposes;
struct Ifc_rel_defines;
struct Ifc_rel_defines_by_properties;
struct Ifc_rel_defines_by_type;
struct Ifc_rel_fills_element;
struct Ifc_rel_flow_control_elements;
struct Ifc_rel_interaction_requirements;
struct Ifc_rel_maintenance_event;
struct Ifc_rel_nests;
struct Ifc_rel_occupies_spaces;
struct Ifc_rel_overrides_properties;
struct Ifc_rel_sequence;
struct Ifc_rel_services_buildings;
struct Ifc_rel_space_boundary;
struct Ifc_rel_uses_resource;
struct Ifc_rel_voids_element;
struct Ifc_relationship;
struct Ifc_representation;
struct Ifc_representation_context;
struct Ifc_representation_item;
struct Ifc_representation_map;
struct Ifc_resource;
struct Ifc_revolved_area_solid;
struct Ifc_roof;
struct Ifc_root;
struct Ifc_rounded_rectangle_profile_def;
struct Ifc_s_i_unit;
struct Ifc_sanitary_terminal;
struct Ifc_schedule_time_control;
struct Ifc_sectioned_spine;
struct Ifc_sensor;
struct Ifc_shape_aspect;
struct Ifc_shape_representation;
struct Ifc_shell_based_surface_model;
struct Ifc_simple_property;
struct Ifc_site;
struct Ifc_slab;
struct Ifc_solid_model;
struct Ifc_space;
struct Ifc_space_program;
struct Ifc_space_program_group;
struct Ifc_space_thermal_load;
struct Ifc_spatial_structure_element;
struct Ifc_spot_light_source;
struct Ifc_stair;
struct Ifc_stair_flight;
struct Ifc_storage_device;
struct Ifc_sub_contract_resource;
struct Ifc_surface;
struct Ifc_surface_extended_properties;
struct Ifc_surface_of_linear_extrusion;
struct Ifc_surface_of_revolution;
struct Ifc_surface_rendering_properties;
struct Ifc_surface_shading_properties;
struct Ifc_surface_style;
struct Ifc_surface_style_properties;
struct Ifc_surface_style_usage;
struct Ifc_swept_area_solid;
struct Ifc_swept_surface;
struct Ifc_system;
struct Ifc_system_furniture_element;
struct Ifc_table;
struct Ifc_table_row;
struct Ifc_tank;
struct Ifc_task;
struct Ifc_telecom_address;
struct Ifc_thermal_material_properties;
struct Ifc_topological_representation_item;
struct Ifc_transport_element;
struct Ifc_trapezium_profile_def;
struct Ifc_treatment_device;
struct Ifc_trimmed_curve;
struct Ifc_tube_bundle;
struct Ifc_type_object;
struct Ifc_type_product;
struct Ifc_unit_assignment;
struct Ifc_unit_heater;
struct Ifc_valve;
struct Ifc_vector;
struct Ifc_vertex;
struct Ifc_vertex_point;
struct Ifc_virtual_grid_intersection;
struct Ifc_wall;
struct Ifc_wall_standard_case;
struct Ifc_window;
struct Ifc_window_lining_properties;
struct Ifc_window_panel_properties;
struct Ifc_window_style;
struct Ifc_work_control;
struct Ifc_work_order;
struct Ifc_work_plan;
struct Ifc_work_schedule;
struct Ifc_zone;

// Base class
struct Ifc {
	std::string entity;
	virtual ~Ifc() {}
};

// Select types (23)
struct Ifc_actor_select {virtual ~Ifc_actor_select() {} };
struct Ifc_axis_2_placement {virtual ~Ifc_axis_2_placement() {} };
struct Ifc_boolean_operand {virtual ~Ifc_boolean_operand() {} };
struct Ifc_classification_notation_select {virtual ~Ifc_classification_notation_select() {} };
struct Ifc_cost_modifier_value_select {virtual ~Ifc_cost_modifier_value_select() {} };
struct Ifc_csg_select {virtual ~Ifc_csg_select() {} };
struct Ifc_date_time_select {virtual ~Ifc_date_time_select() {} };
struct Ifc_derived_measure_value {virtual ~Ifc_derived_measure_value() {} };
struct Ifc_document_select {virtual ~Ifc_document_select() {} };
struct Ifc_f_m_standard_select {virtual ~Ifc_f_m_standard_select() {} };
struct Ifc_geometric_set_select {virtual ~Ifc_geometric_set_select() {} };
struct Ifc_library_select {virtual ~Ifc_library_select() {} };
struct Ifc_material_select {virtual ~Ifc_material_select() {} };
struct Ifc_measure_value {virtual ~Ifc_measure_value() {} };
struct Ifc_metric_value_select {virtual ~Ifc_metric_value_select() {} };
struct Ifc_object_reference_select {virtual ~Ifc_object_reference_select() {} };
struct Ifc_shell {virtual ~Ifc_shell() {} };
struct Ifc_simple_value {virtual ~Ifc_simple_value() {} };
struct Ifc_styled_item_select {virtual ~Ifc_styled_item_select() {} };
struct Ifc_trimming_select {virtual ~Ifc_trimming_select() {} };
struct Ifc_unit {virtual ~Ifc_unit() {} };
struct Ifc_value {virtual ~Ifc_value() {} };
struct Ifc_vector_or_direction {virtual ~Ifc_vector_or_direction() {} };

// Entities (370)
