#ifndef Ifc_parser_h
#define Ifc_parser_h

#include <boost/algorithm/string.hpp>

#include "Step_parser.hpp"

// Defined types (110)
typedef double Ifc_absorbed_dose_measure;
typedef double Ifc_acceleration_measure;
typedef double Ifc_amount_of_substance_measure;
typedef double Ifc_angular_velocity_measure;
typedef double Ifc_area_measure;
typedef bool Ifc_boolean;
typedef std::vector<double> Ifc_complex_number;
typedef std::vector<int> Ifc_compound_plane_angle_measure;
typedef double Ifc_context_dependent_measure;
typedef unsigned int Ifc_count_measure;
typedef double Ifc_curvature_measure;
typedef int Ifc_day_in_month_number;
typedef int Ifc_daylight_saving_hour;
typedef std::string Ifc_descriptive_measure;
typedef int Ifc_dimension_count;
typedef double Ifc_dose_equivalent_measure;
typedef double Ifc_dynamic_viscosity_measure;
typedef double Ifc_electric_capacitance_measure;
typedef double Ifc_electric_charge_measure;
typedef double Ifc_electric_conductance_measure;
typedef double Ifc_electric_current_measure;
typedef double Ifc_electric_resistance_measure;
typedef double Ifc_electric_voltage_measure;
typedef double Ifc_energy_measure;
typedef double Ifc_force_measure;
typedef double Ifc_frequency_measure;
typedef  Ifc_globally_unique_id;
typedef double Ifc_heat_flux_density_measure;
typedef double Ifc_heating_value_measure;
typedef int Ifc_hour_in_day;
typedef std::string Ifc_identifier;
typedef double Ifc_illuminance_measure;
typedef double Ifc_inductance_measure;
typedef int Ifc_integer;
typedef int Ifc_integer_count_rate_measure;
typedef double Ifc_ion_concentration_measure;
typedef double Ifc_isothermal_moisture_capacity_measure;
typedef double Ifc_kinematic_viscosity_measure;
typedef std::string Ifc_label;
typedef double Ifc_length_measure;
typedef double Ifc_linear_force_measure;
typedef double Ifc_linear_moment_measure;
typedef double Ifc_linear_stiffness_measure;
typedef double Ifc_linear_velocity_measure;
typedef int Ifc_logical;
typedef double Ifc_luminous_flux_measure;
typedef double Ifc_luminous_intensity_distribution_measure;
typedef double Ifc_luminous_intensity_measure;
typedef double Ifc_magnetic_flux_density_measure;
typedef double Ifc_magnetic_flux_measure;
typedef double Ifc_mass_density_measure;
typedef double Ifc_mass_flow_rate_measure;
typedef double Ifc_mass_measure;
typedef double Ifc_mass_per_length_measure;
typedef int Ifc_minute_in_hour;
typedef double Ifc_modulus_of_elasticity_measure;
typedef double Ifc_modulus_of_linear_subgrade_reaction_measure;
typedef double Ifc_modulus_of_rotational_subgrade_reaction_measure;
typedef double Ifc_modulus_of_subgrade_reaction_measure;
typedef double Ifc_moisture_diffusivity_measure;
typedef double Ifc_molecular_weight_measure;
typedef double Ifc_moment_of_inertia_measure;
typedef double Ifc_monetary_measure;
typedef int Ifc_month_in_year_number;
typedef unsigned int Ifc_numeric_measure;
typedef double Ifc_p_h_measure;
typedef double Ifc_parameter_value;
typedef double Ifc_planar_force_measure;
typedef double Ifc_plane_angle_measure;
typedef Ifc_length_measure Ifc_positive_length_measure;
typedef Ifc_plane_angle_measure Ifc_positive_plane_angle_measure;
typedef double Ifc_power_measure;
typedef std::string Ifc_presentable_text;
typedef double Ifc_pressure_measure;
typedef double Ifc_radio_activity_measure;
typedef double Ifc_ratio_measure;
typedef double Ifc_real;
typedef double Ifc_rotational_frequency_measure;
typedef double Ifc_rotational_mass_measure;
typedef double Ifc_rotational_stiffness_measure;
typedef double Ifc_second_in_minute;
typedef double Ifc_section_modulus_measure;
typedef double Ifc_sectional_area_integral_measure;
typedef double Ifc_shear_modulus_measure;
typedef double Ifc_solid_angle_measure;
typedef double Ifc_sound_power_measure;
typedef double Ifc_sound_pressure_measure;
typedef double Ifc_specific_heat_capacity_measure;
typedef double Ifc_specular_exponent;
typedef double Ifc_specular_roughness;
typedef double Ifc_temperature_gradient_measure;
typedef std::string Ifc_text;
typedef Ifc_label Ifc_text_alignment;
typedef double Ifc_thermal_admittance_measure;
typedef double Ifc_thermal_conductivity_measure;
typedef double Ifc_thermal_expansion_coefficient_measure;
typedef double Ifc_thermal_resistance_measure;
typedef double Ifc_thermal_transmittance_measure;
typedef double Ifc_thermodynamic_temperature_measure;
typedef double Ifc_time_measure;
typedef int Ifc_time_stamp;
typedef double Ifc_torque_measure;
typedef double Ifc_vapor_permeability_measure;
typedef double Ifc_volume_measure;
typedef double Ifc_volumetric_flow_rate_measure;
typedef double Ifc_warping_constant_measure;
typedef double Ifc_warping_moment_measure;
typedef int Ifc_year_number;
typedef Ifc_ratio_measure Ifc_normalised_ratio_measure;
typedef Ifc_ratio_measure Ifc_positive_ratio_measure;

// Enums (160)
typedef std::string Ifc_action_source_type_enum;
typedef std::string Ifc_action_type_enum;
typedef std::string Ifc_actuator_type_enum;
typedef std::string Ifc_address_type_enum;
typedef std::string Ifc_ahead_or_behind;
typedef std::string Ifc_air_terminal_box_type_enum;
typedef std::string Ifc_air_terminal_type_enum;
typedef std::string Ifc_air_to_air_heat_recovery_type_enum;
typedef std::string Ifc_alarm_type_enum;
typedef std::string Ifc_analysis_model_type_enum;
typedef std::string Ifc_analysis_theory_type_enum;
typedef std::string Ifc_arithmetic_operator_enum;
typedef std::string Ifc_assembly_place_enum;
typedef std::string Ifc_b_spline_curve_form;
typedef std::string Ifc_beam_type_enum;
typedef std::string Ifc_benchmark_enum;
typedef std::string Ifc_boiler_type_enum;
typedef std::string Ifc_boolean_operator;
typedef std::string Ifc_cable_carrier_fitting_type_enum;
typedef std::string Ifc_cable_carrier_segment_type_enum;
typedef std::string Ifc_cable_segment_type_enum;
typedef std::string Ifc_change_action_enum;
typedef std::string Ifc_chiller_type_enum;
typedef std::string Ifc_coil_type_enum;
typedef std::string Ifc_column_type_enum;
typedef std::string Ifc_compressor_type_enum;
typedef std::string Ifc_condenser_type_enum;
typedef std::string Ifc_connection_type_enum;
typedef std::string Ifc_constraint_enum;
typedef std::string Ifc_controller_type_enum;
typedef std::string Ifc_cooled_beam_type_enum;
typedef std::string Ifc_cooling_tower_type_enum;
typedef std::string Ifc_cost_schedule_type_enum;
typedef std::string Ifc_covering_type_enum;
typedef std::string Ifc_currency_enum;
typedef std::string Ifc_damper_type_enum;
typedef std::string Ifc_data_origin_enum;
typedef std::string Ifc_derived_unit_enum;
typedef std::string Ifc_dimension_extent_usage;
typedef std::string Ifc_direction_sense_enum;
typedef std::string Ifc_distribution_chamber_element_type_enum;
typedef std::string Ifc_document_confidentiality_enum;
typedef std::string Ifc_document_status_enum;
typedef std::string Ifc_door_panel_operation_enum;
typedef std::string Ifc_door_panel_position_enum;
typedef std::string Ifc_door_style_construction_enum;
typedef std::string Ifc_door_style_operation_enum;
typedef std::string Ifc_duct_fitting_type_enum;
typedef std::string Ifc_duct_segment_type_enum;
typedef std::string Ifc_duct_silencer_type_enum;
typedef std::string Ifc_electric_appliance_type_enum;
typedef std::string Ifc_electric_current_enum;
typedef std::string Ifc_electric_distribution_point_function_enum;
typedef std::string Ifc_electric_flow_storage_device_type_enum;
typedef std::string Ifc_electric_generator_type_enum;
typedef std::string Ifc_electric_heater_type_enum;
typedef std::string Ifc_electric_motor_type_enum;
typedef std::string Ifc_electric_time_control_type_enum;
typedef std::string Ifc_element_assembly_type_enum;
typedef std::string Ifc_element_composition_enum;
typedef std::string Ifc_energy_sequence_enum;
typedef std::string Ifc_environmental_impact_category_enum;
typedef std::string Ifc_evaporative_cooler_type_enum;
typedef std::string Ifc_evaporator_type_enum;
typedef std::string Ifc_fan_type_enum;
typedef std::string Ifc_filter_type_enum;
typedef std::string Ifc_fire_suppression_terminal_type_enum;
typedef std::string Ifc_flow_direction_enum;
typedef std::string Ifc_flow_instrument_type_enum;
typedef std::string Ifc_flow_meter_type_enum;
typedef std::string Ifc_footing_type_enum;
typedef std::string Ifc_gas_terminal_type_enum;
typedef std::string Ifc_geometric_projection_enum;
typedef std::string Ifc_global_or_local_enum;
typedef std::string Ifc_heat_exchanger_type_enum;
typedef std::string Ifc_humidifier_type_enum;
typedef std::string Ifc_internal_or_external_enum;
typedef std::string Ifc_inventory_type_enum;
typedef std::string Ifc_junction_box_type_enum;
typedef std::string Ifc_layer_set_direction_enum;
typedef std::string Ifc_light_distribution_curve_enum;
typedef std::string Ifc_light_emission_source_enum;
typedef std::string Ifc_light_fixture_type_enum;
typedef std::string Ifc_load_group_type_enum;
typedef std::string Ifc_logical_operator_enum;
typedef std::string Ifc_member_type_enum;
typedef std::string Ifc_motor_connection_type_enum;
typedef std::string Ifc_null_style;
typedef std::string Ifc_object_type_enum;
typedef std::string Ifc_objective_enum;
typedef std::string Ifc_occupant_type_enum;
typedef std::string Ifc_outlet_type_enum;
typedef std::string Ifc_permeable_covering_operation_enum;
typedef std::string Ifc_physical_or_virtual_enum;
typedef std::string Ifc_pile_construction_enum;
typedef std::string Ifc_pile_type_enum;
typedef std::string Ifc_pipe_fitting_type_enum;
typedef std::string Ifc_pipe_segment_type_enum;
typedef std::string Ifc_plate_type_enum;
typedef std::string Ifc_procedure_type_enum;
typedef std::string Ifc_profile_type_enum;
typedef std::string Ifc_project_order_record_type_enum;
typedef std::string Ifc_project_order_type_enum;
typedef std::string Ifc_projected_or_true_length_enum;
typedef std::string Ifc_property_source_enum;
typedef std::string Ifc_protective_device_type_enum;
typedef std::string Ifc_pump_type_enum;
typedef std::string Ifc_railing_type_enum;
typedef std::string Ifc_ramp_flight_type_enum;
typedef std::string Ifc_ramp_type_enum;
typedef std::string Ifc_reflectance_method_enum;
typedef std::string Ifc_reinforcing_bar_role_enum;
typedef std::string Ifc_reinforcing_bar_surface_enum;
typedef std::string Ifc_resource_consumption_enum;
typedef std::string Ifc_rib_plate_direction_enum;
typedef std::string Ifc_role_enum;
typedef std::string Ifc_roof_type_enum;
typedef std::string Ifc_s_i_prefix;
typedef std::string Ifc_s_i_unit_name;
typedef std::string Ifc_sanitary_terminal_type_enum;
typedef std::string Ifc_section_type_enum;
typedef std::string Ifc_sensor_type_enum;
typedef std::string Ifc_sequence_enum;
typedef std::string Ifc_service_life_factor_type_enum;
typedef std::string Ifc_service_life_type_enum;
typedef std::string Ifc_slab_type_enum;
typedef std::string Ifc_sound_scale_enum;
typedef std::string Ifc_space_heater_type_enum;
typedef std::string Ifc_stack_terminal_type_enum;
typedef std::string Ifc_stair_flight_type_enum;
typedef std::string Ifc_stair_type_enum;
typedef std::string Ifc_state_enum;
typedef std::string Ifc_structural_curve_type_enum;
typedef std::string Ifc_structural_surface_type_enum;
typedef std::string Ifc_surface_side;
typedef std::string Ifc_surface_texture_enum;
typedef std::string Ifc_switching_device_type_enum;
typedef std::string Ifc_tank_type_enum;
typedef std::string Ifc_tendon_type_enum;
typedef std::string Ifc_text_path;
typedef std::string Ifc_thermal_load_source_enum;
typedef std::string Ifc_thermal_load_type_enum;
typedef std::string Ifc_time_series_data_type_enum;
typedef std::string Ifc_time_series_schedule_type_enum;
typedef std::string Ifc_transformer_type_enum;
typedef std::string Ifc_transition_code;
typedef std::string Ifc_transport_element_type_enum;
typedef std::string Ifc_trimming_preference;
typedef std::string Ifc_tube_bundle_type_enum;
typedef std::string Ifc_unit_enum;
typedef std::string Ifc_unitary_equipment_type_enum;
typedef std::string Ifc_valve_type_enum;
typedef std::string Ifc_vibration_isolator_type_enum;
typedef std::string Ifc_wall_type_enum;
typedef std::string Ifc_waste_terminal_type_enum;
typedef std::string Ifc_window_panel_operation_enum;
typedef std::string Ifc_window_panel_position_enum;
typedef std::string Ifc_window_style_construction_enum;
typedef std::string Ifc_window_style_operation_enum;
typedef std::string Ifc_work_control_type_enum;

// Forward declarations (623)
struct Ifc_2_d_composite_curve;
struct Ifc_action_request;
struct Ifc_actor;
struct Ifc_actor_role;
struct Ifc_actuator_type;
struct Ifc_address;
struct Ifc_air_terminal_box_type;
struct Ifc_air_terminal_type;
struct Ifc_air_to_air_heat_recovery_type;
struct Ifc_alarm_type;
struct Ifc_angular_dimension;
struct Ifc_annotation;
struct Ifc_annotation_curve_occurrence;
struct Ifc_annotation_fill_area;
struct Ifc_annotation_fill_area_occurrence;
struct Ifc_annotation_occurrence;
struct Ifc_annotation_surface_occurrence;
struct Ifc_annotation_symbol_occurrence;
struct Ifc_annotation_text_occurrence;
struct Ifc_application;
struct Ifc_applied_value;
struct Ifc_applied_value_relationship;
struct Ifc_approval;
struct Ifc_approval_actor_relationship;
struct Ifc_approval_property_relationship;
struct Ifc_approval_relationship;
struct Ifc_arbitrary_closed_profile_def;
struct Ifc_arbitrary_open_profile_def;
struct Ifc_arbitrary_profile_def_with_voids;
struct Ifc_asset;
struct Ifc_asymmetric_i_shape_profile_def;
struct Ifc_axis_1_placement;
struct Ifc_axis_2_placement_2_d;
struct Ifc_axis_2_placement_3_d;
struct Ifc_b_spline_curve;
struct Ifc_beam;
struct Ifc_beam_and_column_type;
struct Ifc_beam_type;
struct Ifc_bezier_curve;
struct Ifc_boiler_type;
struct Ifc_boolean_clipping_result;
struct Ifc_boolean_result;
struct Ifc_boundary_condition;
struct Ifc_boundary_edge_condition;
struct Ifc_boundary_face_condition;
struct Ifc_boundary_node_condition;
struct Ifc_boundary_node_condition_warping;
struct Ifc_bounded_curve;
struct Ifc_bounded_surface;
struct Ifc_bounding_box;
struct Ifc_boxed_half_space;
struct Ifc_building;
struct Ifc_building_element;
struct Ifc_building_element_component;
struct Ifc_building_element_component_type;
struct Ifc_building_element_part;
struct Ifc_building_element_proxy;
struct Ifc_building_element_type;
struct Ifc_building_storey;
struct Ifc_c_shape_profile_def;
struct Ifc_cable_carrier_fitting_type;
struct Ifc_cable_carrier_segment_type;
struct Ifc_cable_segment_type;
struct Ifc_calendar_date;
struct Ifc_cartesian_point;
struct Ifc_cartesian_transformation_operator;
struct Ifc_cartesian_transformation_operator_2_d;
struct Ifc_cartesian_transformation_operator_2_dnon_uniform;
struct Ifc_cartesian_transformation_operator_3_d;
struct Ifc_cartesian_transformation_operator_3_dnon_uniform;
struct Ifc_chamfer_edge_feature;
struct Ifc_chiller_type;
struct Ifc_circle;
struct Ifc_circle_hollow_profile_def;
struct Ifc_circle_profile_def;
struct Ifc_classification;
struct Ifc_classification_item;
struct Ifc_classification_item_relationship;
struct Ifc_classification_notation;
struct Ifc_classification_notation_facet;
struct Ifc_classification_reference;
struct Ifc_closed_shell;
struct Ifc_coil_type;
struct Ifc_colour_rgb;
struct Ifc_colour_specification;
struct Ifc_column;
struct Ifc_column_type;
struct Ifc_complex_property;
struct Ifc_composite_curve;
struct Ifc_composite_curve_segment;
struct Ifc_composite_profile_def;
struct Ifc_compressor_type;
struct Ifc_condenser_type;
struct Ifc_condition;
struct Ifc_condition_criterion;
struct Ifc_conic;
struct Ifc_connected_face_set;
struct Ifc_connection_curve_geometry;
struct Ifc_connection_geometry;
struct Ifc_connection_point_geometry;
struct Ifc_connection_port_geometry;
struct Ifc_connection_surface_geometry;
struct Ifc_constraint;
struct Ifc_constraint_aggregation_relationship;
struct Ifc_construction_equipment_resource;
struct Ifc_construction_material_resource;
struct Ifc_construction_product_resource;
struct Ifc_construction_resource;
struct Ifc_context_dependent_unit;
struct Ifc_control;
struct Ifc_controller_type;
struct Ifc_conversion_based_unit;
struct Ifc_cooled_beam_type;
struct Ifc_cooling_tower_type;
struct Ifc_coordinated_universal_time_offset;
struct Ifc_cost_item;
struct Ifc_cost_schedule;
struct Ifc_cost_value;
struct Ifc_covering;
struct Ifc_covering_type;
struct Ifc_crane_rail_a_shape_profile_def;
struct Ifc_crane_rail_f_shape_profile_def;
struct Ifc_crew_resource;
struct Ifc_csg_solid;
struct Ifc_currency_relationship;
struct Ifc_curtain_wall;
struct Ifc_curve;
struct Ifc_curve_bounded_plane;
struct Ifc_curve_style;
struct Ifc_curve_style_font;
struct Ifc_curve_style_font_and_scaling;
struct Ifc_curve_style_font_pattern;
struct Ifc_damper_type;
struct Ifc_date_and_time;
struct Ifc_defined_symbol;
struct Ifc_derived_profile_def;
struct Ifc_derived_unit;
struct Ifc_derived_unit_element;
struct Ifc_diameter_dimension;
struct Ifc_dimension_callout_relationship;
struct Ifc_dimension_curve;
struct Ifc_dimension_curve_directed_callout;
struct Ifc_dimension_curve_terminator;
struct Ifc_dimensional_exponents;
struct Ifc_direction;
struct Ifc_discrete_accessory;
struct Ifc_discrete_accessory_type;
struct Ifc_distribution_chamber_element;
struct Ifc_distribution_chamber_element_type;
struct Ifc_distribution_control_element;
struct Ifc_distribution_control_element_type;
struct Ifc_distribution_element;
struct Ifc_distribution_element_type;
struct Ifc_distribution_flow_element;
struct Ifc_distribution_flow_element_type;
struct Ifc_distribution_port;
struct Ifc_document_electronic_format;
struct Ifc_document_information;
struct Ifc_document_information_relationship;
struct Ifc_document_reference;
struct Ifc_door;
struct Ifc_door_lining_properties;
struct Ifc_door_panel_properties;
struct Ifc_door_style;
struct Ifc_draughting_callout;
struct Ifc_draughting_callout_relationship;
struct Ifc_draughting_pre_defined_colour;
struct Ifc_draughting_pre_defined_curve_font;
struct Ifc_draughting_pre_defined_text_font;
struct Ifc_duct_fitting_type;
struct Ifc_duct_segment_type;
struct Ifc_duct_silencer_type;
struct Ifc_edge;
struct Ifc_edge_curve;
struct Ifc_edge_feature;
struct Ifc_edge_loop;
struct Ifc_electric_appliance_type;
struct Ifc_electric_distribution_point;
struct Ifc_electric_flow_storage_device_type;
struct Ifc_electric_generator_type;
struct Ifc_electric_heater_type;
struct Ifc_electric_motor_type;
struct Ifc_electric_time_control_type;
struct Ifc_electrical_base_properties;
struct Ifc_electrical_circuit;
struct Ifc_electrical_element;
struct Ifc_element;
struct Ifc_element_assembly;
struct Ifc_element_component;
struct Ifc_element_component_type;
struct Ifc_element_quantity;
struct Ifc_element_type;
struct Ifc_elementary_surface;
struct Ifc_ellipse;
struct Ifc_ellipse_profile_def;
struct Ifc_energy_conversion_device;
struct Ifc_energy_conversion_device_type;
struct Ifc_energy_properties;
struct Ifc_environmental_impact_value;
struct Ifc_equipment_element;
struct Ifc_equipment_standard;
struct Ifc_evaporative_cooler_type;
struct Ifc_evaporator_type;
struct Ifc_extended_material_properties;
struct Ifc_external_reference;
struct Ifc_externally_defined_hatch_style;
struct Ifc_externally_defined_suface_style;
struct Ifc_externally_defined_symbol;
struct Ifc_externally_defined_text_font;
struct Ifc_extruded_area_solid;
struct Ifc_face;
struct Ifc_face_based_surface_model;
struct Ifc_face_bound;
struct Ifc_face_outer_bound;
struct Ifc_face_surface;
struct Ifc_faceted_brep;
struct Ifc_faceted_brep_with_voids;
struct Ifc_failure_connection_condition;
struct Ifc_fan_type;
struct Ifc_fastener;
struct Ifc_fastener_type;
struct Ifc_feature_element;
struct Ifc_feature_element_addition;
struct Ifc_feature_element_subtraction;
struct Ifc_fill_area_style;
struct Ifc_fill_area_style_hatching;
struct Ifc_fill_area_style_tile_symbol_with_style;
struct Ifc_fill_area_style_tiles;
struct Ifc_filter_type;
struct Ifc_fire_suppression_terminal_type;
struct Ifc_flow_controller;
struct Ifc_flow_controller_type;
struct Ifc_flow_fitting;
struct Ifc_flow_fitting_type;
struct Ifc_flow_instrument_type;
struct Ifc_flow_meter_type;
struct Ifc_flow_moving_device;
struct Ifc_flow_moving_device_type;
struct Ifc_flow_segment;
struct Ifc_flow_segment_type;
struct Ifc_flow_storage_device;
struct Ifc_flow_storage_device_type;
struct Ifc_flow_terminal;
struct Ifc_flow_terminal_type;
struct Ifc_flow_treatment_device;
struct Ifc_flow_treatment_device_type;
struct Ifc_fluid_flow_properties;
struct Ifc_footing;
struct Ifc_fuel_properties;
struct Ifc_furnishing_element;
struct Ifc_furnishing_element_type;
struct Ifc_furniture_standard;
struct Ifc_furniture_type;
struct Ifc_gas_terminal_type;
struct Ifc_general_material_properties;
struct Ifc_general_profile_properties;
struct Ifc_geometric_curve_set;
struct Ifc_geometric_representation_context;
struct Ifc_geometric_representation_item;
struct Ifc_geometric_representation_sub_context;
struct Ifc_geometric_set;
struct Ifc_grid;
struct Ifc_grid_axis;
struct Ifc_grid_placement;
struct Ifc_group;
struct Ifc_half_space_solid;
struct Ifc_heat_exchanger_type;
struct Ifc_humidifier_type;
struct Ifc_hygroscopic_material_properties;
struct Ifc_i_shape_profile_def;
struct Ifc_image_texture;
struct Ifc_inventory;
struct Ifc_irregular_time_series;
struct Ifc_irregular_time_series_value;
struct Ifc_junction_box_type;
struct Ifc_l_shape_profile_def;
struct Ifc_labor_resource;
struct Ifc_library_information;
struct Ifc_library_reference;
struct Ifc_light_distribution_data;
struct Ifc_light_fixture_type;
struct Ifc_light_intensity_distribution;
struct Ifc_light_source;
struct Ifc_light_source_ambient;
struct Ifc_light_source_directional;
struct Ifc_light_source_goniometric;
struct Ifc_light_source_positional;
struct Ifc_light_source_spot;
struct Ifc_line;
struct Ifc_linear_dimension;
struct Ifc_local_placement;
struct Ifc_local_time;
struct Ifc_loop;
struct Ifc_manifold_solid_brep;
struct Ifc_mapped_item;
struct Ifc_material;
struct Ifc_material_classification_relationship;
struct Ifc_material_layer;
struct Ifc_material_layer_set;
struct Ifc_material_layer_set_usage;
struct Ifc_material_list;
struct Ifc_material_properties;
struct Ifc_measure_with_unit;
struct Ifc_mechanical_concrete_material_properties;
struct Ifc_mechanical_fastener;
struct Ifc_mechanical_fastener_type;
struct Ifc_mechanical_material_properties;
struct Ifc_mechanical_steel_material_properties;
struct Ifc_member_type;
struct Ifc_metric;
struct Ifc_monetary_unit;
struct Ifc_motor_connection_type;
struct Ifc_move;
struct Ifc_named_unit;
struct Ifc_object;
struct Ifc_object_placement;
struct Ifc_objective;
struct Ifc_occupant;
struct Ifc_offset_curve_2_d;
struct Ifc_offset_curve_3_d;
struct Ifc_one_direction_repeat_factor;
struct Ifc_open_shell;
struct Ifc_opening_element;
struct Ifc_optical_material_properties;
struct Ifc_order_action;
struct Ifc_organization;
struct Ifc_organization_relationship;
struct Ifc_oriented_edge;
struct Ifc_outlet_type;
struct Ifc_owner_history;
struct Ifc_parameterized_profile_def;
struct Ifc_path;
struct Ifc_performance_history;
struct Ifc_permeable_covering_properties;
struct Ifc_permit;
struct Ifc_person;
struct Ifc_person_and_organization;
struct Ifc_physical_quantity;
struct Ifc_pile;
struct Ifc_pipe_fitting_type;
struct Ifc_pipe_segment_type;
struct Ifc_pixel_texture;
struct Ifc_placement;
struct Ifc_planar_box;
struct Ifc_planar_extent;
struct Ifc_plane;
struct Ifc_plate;
struct Ifc_plate_type;
struct Ifc_point;
struct Ifc_point_on_curve;
struct Ifc_point_on_surface;
struct Ifc_poly_loop;
struct Ifc_polygonal_bounded_half_space;
struct Ifc_polyline;
struct Ifc_port;
struct Ifc_postal_address;
struct Ifc_pre_defined_colour;
struct Ifc_pre_defined_curve_font;
struct Ifc_pre_defined_dimension_symbol;
struct Ifc_pre_defined_item;
struct Ifc_pre_defined_point_marker_symbol;
struct Ifc_pre_defined_symbol;
struct Ifc_pre_defined_terminator_symbol;
struct Ifc_pre_defined_text_font;
struct Ifc_presentation_layer_assignment;
struct Ifc_presentation_layer_assignment_with_style;
struct Ifc_presentation_style_assignment;
struct Ifc_procedure;
struct Ifc_process;
struct Ifc_product;
struct Ifc_product_definition_shape;
struct Ifc_product_representation;
struct Ifc_products_of_combustion_properties;
struct Ifc_profile_def;
struct Ifc_profile_properties;
struct Ifc_project;
struct Ifc_project_order;
struct Ifc_project_order_record;
struct Ifc_projection_curve;
struct Ifc_projection_element;
struct Ifc_property;
struct Ifc_property_bounded_value;
struct Ifc_property_constraint_relationship;
struct Ifc_property_definition;
struct Ifc_property_dependency_relationship;
struct Ifc_property_enumerated_value;
struct Ifc_property_enumeration;
struct Ifc_property_list_value;
struct Ifc_property_reference_value;
struct Ifc_property_set;
struct Ifc_property_set_definition;
struct Ifc_property_single_value;
struct Ifc_property_table_value;
struct Ifc_protective_device_type;
struct Ifc_proxy;
struct Ifc_pump_type;
struct Ifc_quantity_area;
struct Ifc_quantity_count;
struct Ifc_quantity_length;
struct Ifc_quantity_time;
struct Ifc_quantity_volume;
struct Ifc_quantity_weight;
struct Ifc_radius_dimension;
struct Ifc_railing;
struct Ifc_railing_type;
struct Ifc_ramp;
struct Ifc_ramp_flight;
struct Ifc_ramp_flight_type;
struct Ifc_rational_bezier_curve;
struct Ifc_rectangle_hollow_profile_def;
struct Ifc_rectangle_profile_def;
struct Ifc_rectangular_trimmed_surface;
struct Ifc_references_value_document;
struct Ifc_regular_time_series;
struct Ifc_reinforcement_bar_properties;
struct Ifc_reinforcement_definition_properties;
struct Ifc_reinforcing_bar;
struct Ifc_reinforcing_element;
struct Ifc_reinforcing_mesh;
struct Ifc_rel_aggregates;
struct Ifc_rel_assigns;
struct Ifc_rel_assigns_tasks;
struct Ifc_rel_assigns_to_actor;
struct Ifc_rel_assigns_to_control;
struct Ifc_rel_assigns_to_group;
struct Ifc_rel_assigns_to_process;
struct Ifc_rel_assigns_to_product;
struct Ifc_rel_assigns_to_project_order;
struct Ifc_rel_assigns_to_resource;
struct Ifc_rel_associates;
struct Ifc_rel_associates_applied_value;
struct Ifc_rel_associates_approval;
struct Ifc_rel_associates_classification;
struct Ifc_rel_associates_constraint;
struct Ifc_rel_associates_document;
struct Ifc_rel_associates_library;
struct Ifc_rel_associates_material;
struct Ifc_rel_associates_profile_properties;
struct Ifc_rel_connects;
struct Ifc_rel_connects_elements;
struct Ifc_rel_connects_path_elements;
struct Ifc_rel_connects_port_to_element;
struct Ifc_rel_connects_ports;
struct Ifc_rel_connects_structural_activity;
struct Ifc_rel_connects_structural_member;
struct Ifc_rel_connects_with_realizing_elements;
struct Ifc_rel_contained_in_spatial_structure;
struct Ifc_rel_covers_bldg_elements;
struct Ifc_rel_decomposes;
struct Ifc_rel_defines;
struct Ifc_rel_defines_by_properties;
struct Ifc_rel_defines_by_type;
struct Ifc_rel_fills_element;
struct Ifc_rel_flow_control_elements;
struct Ifc_rel_interaction_requirements;
struct Ifc_rel_nests;
struct Ifc_rel_occupies_spaces;
struct Ifc_rel_overrides_properties;
struct Ifc_rel_projects_element;
struct Ifc_rel_schedules_cost_items;
struct Ifc_rel_sequence;
struct Ifc_rel_services_buildings;
struct Ifc_rel_space_boundary;
struct Ifc_rel_voids_element;
struct Ifc_relationship;
struct Ifc_relaxation;
struct Ifc_representation;
struct Ifc_representation_context;
struct Ifc_representation_item;
struct Ifc_representation_map;
struct Ifc_resource;
struct Ifc_revolved_area_solid;
struct Ifc_rib_plate_profile_properties;
struct Ifc_roof;
struct Ifc_root;
struct Ifc_rounded_edge_feature;
struct Ifc_rounded_rectangle_profile_def;
struct Ifc_s_i_unit;
struct Ifc_sanitary_terminal_type;
struct Ifc_schedule_time_control;
struct Ifc_section_properties;
struct Ifc_section_reinforcement_properties;
struct Ifc_sectioned_spine;
struct Ifc_sensor_type;
struct Ifc_service_life;
struct Ifc_service_life_factor;
struct Ifc_shape_aspect;
struct Ifc_shape_representation;
struct Ifc_shell_based_surface_model;
struct Ifc_simple_property;
struct Ifc_site;
struct Ifc_slab;
struct Ifc_slab_type;
struct Ifc_slippage_connection_condition;
struct Ifc_solid_model;
struct Ifc_sound_properties;
struct Ifc_sound_value;
struct Ifc_space;
struct Ifc_space_heater_type;
struct Ifc_space_program;
struct Ifc_space_thermal_load_properties;
struct Ifc_spatial_structure_element;
struct Ifc_stack_terminal_type;
struct Ifc_stair;
struct Ifc_stair_flight;
struct Ifc_stair_flight_type;
struct Ifc_structural_action;
struct Ifc_structural_activity;
struct Ifc_structural_analysis_model;
struct Ifc_structural_connection;
struct Ifc_structural_connection_condition;
struct Ifc_structural_curve_connection;
struct Ifc_structural_curve_member;
struct Ifc_structural_curve_member_varying;
struct Ifc_structural_item;
struct Ifc_structural_linear_action;
struct Ifc_structural_linear_action_varying;
struct Ifc_structural_load;
struct Ifc_structural_load_group;
struct Ifc_structural_load_linear_force;
struct Ifc_structural_load_planar_force;
struct Ifc_structural_load_single_displacement;
struct Ifc_structural_load_single_displacement_distortion;
struct Ifc_structural_load_single_force;
struct Ifc_structural_load_single_force_warping;
struct Ifc_structural_load_static;
struct Ifc_structural_load_temperature;
struct Ifc_structural_member;
struct Ifc_structural_planar_action;
struct Ifc_structural_planar_action_varying;
struct Ifc_structural_point_action;
struct Ifc_structural_point_connection;
struct Ifc_structural_point_reaction;
struct Ifc_structural_profile_properties;
struct Ifc_structural_reaction;
struct Ifc_structural_result_group;
struct Ifc_structural_steel_profile_properties;
struct Ifc_structural_surface_connection;
struct Ifc_structural_surface_member;
struct Ifc_structural_surface_member_varying;
struct Ifc_structured_dimension_callout;
struct Ifc_styled_item;
struct Ifc_styled_representation;
struct Ifc_sub_contract_resource;
struct Ifc_subedge;
struct Ifc_surface;
struct Ifc_surface_curve_swept_area_solid;
struct Ifc_surface_of_linear_extrusion;
struct Ifc_surface_of_revolution;
struct Ifc_surface_style;
struct Ifc_surface_style_lighting;
struct Ifc_surface_style_refraction;
struct Ifc_surface_style_rendering;
struct Ifc_surface_style_shading;
struct Ifc_surface_style_with_textures;
struct Ifc_surface_texture;
struct Ifc_swept_area_solid;
struct Ifc_swept_disk_solid;
struct Ifc_swept_surface;
struct Ifc_switching_device_type;
struct Ifc_symbol_style;
struct Ifc_system;
struct Ifc_system_furniture_element_type;
struct Ifc_t_shape_profile_def;
struct Ifc_table;
struct Ifc_table_row;
struct Ifc_tank_type;
struct Ifc_task;
struct Ifc_telecom_address;
struct Ifc_tendon;
struct Ifc_tendon_anchor;
struct Ifc_terminator_symbol;
struct Ifc_text_literal;
struct Ifc_text_literal_with_extent;
struct Ifc_text_style;
struct Ifc_text_style_with_box_characteristics;
struct Ifc_text_style_with_mirror;
struct Ifc_text_style_with_spacing;
struct Ifc_texture_coordinate;
struct Ifc_texture_coordinate_generator;
struct Ifc_texture_map;
struct Ifc_texture_vertex;
struct Ifc_thermal_material_properties;
struct Ifc_time_series;
struct Ifc_time_series_reference_relationship;
struct Ifc_time_series_schedule;
struct Ifc_time_series_value;
struct Ifc_topological_representation_item;
struct Ifc_topology_representation;
struct Ifc_transformer_type;
struct Ifc_transport_element;
struct Ifc_transport_element_type;
struct Ifc_trapezium_profile_def;
struct Ifc_trimmed_curve;
struct Ifc_tube_bundle_type;
struct Ifc_two_direction_repeat_factor;
struct Ifc_type_object;
struct Ifc_type_product;
struct Ifc_u_shape_profile_def;
struct Ifc_unit_assignment;
struct Ifc_unitary_equipment_type;
struct Ifc_valve_type;
struct Ifc_vector;
struct Ifc_vertex;
struct Ifc_vertex_based_texture_map;
struct Ifc_vertex_loop;
struct Ifc_vertex_point;
struct Ifc_vibration_isolator_type;
struct Ifc_virtual_grid_intersection;
struct Ifc_wall;
struct Ifc_wall_standard_case;
struct Ifc_wall_type;
struct Ifc_waste_terminal_type;
struct Ifc_water_properties;
struct Ifc_window;
struct Ifc_window_lining_properties;
struct Ifc_window_panel_properties;
struct Ifc_window_style;
struct Ifc_work_control;
struct Ifc_work_plan;
struct Ifc_work_schedule;
struct Ifc_z_shape_profile_def;
struct Ifc_zone;

// Base class
struct Ifc {
	std::string entity;
	virtual ~Ifc() {}
};

// Select types (42)
struct Ifc_actor_select {virtual ~Ifc_actor_select() {} };
struct Ifc_applied_value_select {virtual ~Ifc_applied_value_select() {} };
struct Ifc_axis_2_placement {virtual ~Ifc_axis_2_placement() {} };
struct Ifc_boolean_operand {virtual ~Ifc_boolean_operand() {} };
struct Ifc_character_spacing_select {virtual ~Ifc_character_spacing_select() {} };
struct Ifc_character_style_select {virtual ~Ifc_character_style_select() {} };
struct Ifc_classification_notation_select {virtual ~Ifc_classification_notation_select() {} };
struct Ifc_colour {virtual ~Ifc_colour() {} };
struct Ifc_colour_or_factor {virtual ~Ifc_colour_or_factor() {} };
struct Ifc_condition_criterion_select {virtual ~Ifc_condition_criterion_select() {} };
struct Ifc_csg_select {virtual ~Ifc_csg_select() {} };
struct Ifc_curve_font_or_scaled_curve_font_select {virtual ~Ifc_curve_font_or_scaled_curve_font_select() {} };
struct Ifc_curve_style_font_select {virtual ~Ifc_curve_style_font_select() {} };
struct Ifc_date_time_select {virtual ~Ifc_date_time_select() {} };
struct Ifc_defined_symbol_select {virtual ~Ifc_defined_symbol_select() {} };
struct Ifc_derived_measure_value {virtual ~Ifc_derived_measure_value() {} };
struct Ifc_document_select {virtual ~Ifc_document_select() {} };
struct Ifc_draughting_callout_element {virtual ~Ifc_draughting_callout_element() {} };
struct Ifc_fill_area_style_tile_shape_select {virtual ~Ifc_fill_area_style_tile_shape_select() {} };
struct Ifc_fill_style_select {virtual ~Ifc_fill_style_select() {} };
struct Ifc_font_select {virtual ~Ifc_font_select() {} };
struct Ifc_geometric_set_select {virtual ~Ifc_geometric_set_select() {} };
struct Ifc_layered_item {virtual ~Ifc_layered_item() {} };
struct Ifc_library_select {virtual ~Ifc_library_select() {} };
struct Ifc_light_distribution_data_source_select {virtual ~Ifc_light_distribution_data_source_select() {} };
struct Ifc_material_select {virtual ~Ifc_material_select() {} };
struct Ifc_measure_value {virtual ~Ifc_measure_value() {} };
struct Ifc_metric_value_select {virtual ~Ifc_metric_value_select() {} };
struct Ifc_object_reference_select {virtual ~Ifc_object_reference_select() {} };
struct Ifc_presentation_style_select {virtual ~Ifc_presentation_style_select() {} };
struct Ifc_shell {virtual ~Ifc_shell() {} };
struct Ifc_simple_value {virtual ~Ifc_simple_value() {} };
struct Ifc_size_select {virtual ~Ifc_size_select() {} };
struct Ifc_specular_highlight_select {virtual ~Ifc_specular_highlight_select() {} };
struct Ifc_structural_activity_assignment_select {virtual ~Ifc_structural_activity_assignment_select() {} };
struct Ifc_surface_style_element_select {virtual ~Ifc_surface_style_element_select() {} };
struct Ifc_symbol_style_select {virtual ~Ifc_symbol_style_select() {} };
struct Ifc_text_style_select {virtual ~Ifc_text_style_select() {} };
struct Ifc_trimming_select {virtual ~Ifc_trimming_select() {} };
struct Ifc_unit {virtual ~Ifc_unit() {} };
struct Ifc_value {virtual ~Ifc_value() {} };
struct Ifc_vector_or_direction {virtual ~Ifc_vector_or_direction() {} };

// Entities (623)
